<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
    <Version>0.5.1</Version>
    <Authors>gmoddev</Authors>
    <RepositoryUrl>https://github.com/gmoddev/VpnProController</RepositoryUrl>
  </PropertyGroup>
</Project>
